import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ["pino", "pino-pretty"],
  compress: true,
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 86400, // 24 hours — was 60s
  },
  experimental: {
    optimizePackageImports: ["lucide-react", "@radix-ui/react-icons"],
  },
  compiler: {
    removeConsole: process.env.NODE_ENV === "production" ? { exclude: ["error", "warn"] } : false,
  },
    async redirects() {
    return [
      { source: "/tools/time/sleep-latency", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-efficiency", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-debt", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-log", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-efficiency-tracker", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/circadian-shift-planner", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/shift-circadian", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-latency-calc", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/rem-sleep-clock", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/rem-sleep-alarm", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/sleep-onset-clock", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/rem-bedtime-clock", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/time/rem-latency-bedtime-clock", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/health/sleep-quality", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/health/sleep-planner", destination: "/tools/health/sleep-calculator", permanent: true },
      { source: "/tools/util/phonetic-password-nato", destination: "/tools/util/phonetic-password", permanent: true },
      { source: "/tools/util/nato-phonetic-password", destination: "/tools/util/phonetic-password", permanent: true },
      { source: "/tools/util/nato-password-reader", destination: "/tools/util/phonetic-password", permanent: true },
      { source: "/tools/image/color-matrix", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/color-contrast-extractor", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/contrast-table", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/contrast-matrix-export", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/contrast-compliance-sheet", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/contrast-sheet-exporter", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/image/contrast-matrix-sheet", destination: "/tools/image/color-contrast-checker", permanent: true },
      { source: "/tools/health/pace-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/swimming-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/cycling-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/hiking-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/jumprope-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/rowing-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/elliptical-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/stair-climbing-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/indoor-cycling-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/recumbent-bike-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/health/stair-stepper-calorie", destination: "/tools/health/calorie-activity", permanent: true },
      { source: "/tools/productivity/priority-matrix", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-planner", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-kanban", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/priority-kanban", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-list", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/priority-matrix-2x2", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-goals", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-board", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-checklist", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/eisenhower-workspace", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/priority-action-planner", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/priority-quadrant-board", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/productivity/daily-priority-action-board", destination: "/tools/productivity/eisenhower-matrix", permanent: true },
      { source: "/tools/travel/currency-matrix", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/exchange-table", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/currency-card", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/exchange-trend", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/currency-price-matrix", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/travel-budget-matrix", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/trip-budget-matrix", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/travel-budget-sheet", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/travel-budget-calc-sheet", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/travel/multi-country-budget-sheet", destination: "/tools/travel/travel-budget-planner", permanent: true },
      { source: "/tools/time/time-capsule", destination: "/tools", permanent: true },
      { source: "/tools/util/morse-flashlight", destination: "/tools", permanent: true },
      { source: "/tools/finance/currency-slang", destination: "/tools", permanent: true },
      { source: "/tools/fun/love-calculator", destination: "/tools", permanent: true },
      { source: "/tools/fun/morse-audio", destination: "/tools", permanent: true },
      { source: "/tools/fun/animal-quiz", destination: "/tools", permanent: true },
      { source: "/tools/fun/compound-words", destination: "/tools", permanent: true }
    ];
  },
  headers: async () => [
    {
      source: "/(.*)",
      headers: [
        { key: "X-Content-Type-Options", value: "nosniff" },
        { key: "X-Frame-Options", value: "DENY" },
        { key: "X-XSS-Protection", value: "1; mode=block" },
        { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        { key: "Strict-Transport-Security", value: "max-age=31536000; includeSubDomains" },
        { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
      ],
    },
  ],
};

export default nextConfig;
