import JsonLd from "@/components/seo/json-ld";
import { buildMetadata, buildToolJsonLd } from "@/lib/seo";
import AiDetectorClient from "@/components/tools/writing/ai-detector-client";

const TITLE = "Free AI Content Detector - Check ChatGPT, Claude & AI Text Online";
const DESCRIPTION =
  "Detect text generated by ChatGPT (GPT-4o), Claude 3.5, Gemini, and DeepSeek. Free AI detector with sentence-by-sentence perplexity heatmaps, burstiness analysis, and 100% privacy.";
const PATH = "/tools/writing/ai-detector";

export const metadata = buildMetadata({
  title: TITLE,
  description: DESCRIPTION,
  path: PATH,
  keywords: [
    "ai detector",
    "chatgpt detector",
    "ai content checker",
    "ai essay checker",
    "free ai detector",
    "gpt zero alternative",
    "detect ai writing",
    "claude detector",
    "perplexity checker",
    "ai text authenticity",
  ],
});

export default function Page() {
  const jsonLd = buildToolJsonLd({
    name: "Free AI Content Detector & Authenticity Checker",
    description: DESCRIPTION,
    path: PATH,
  });

  return (
    <>
      <JsonLd data={jsonLd} />
      <AiDetectorClient />
    </>
  );
}
